apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-deployment
  labels:
    app: {{ .Values.lable }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.lable }}
  template:
    metadata:
      labels:
        app: {{ .Values.lable }}
    spec:
      containers:
      - name: {{ .Values.image.name }}
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        ports:
        - containerPort: 3000
        env:
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: {{ .Values.appname }}-secret
              key: USER_NAME
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Values.appname }}-secret
              key: PASSWORD
        - name: POSTGRES_HOST
          valueFrom:
            secretKeyRef:
              name: {{ .Values.appname }}-secret
              key: HOST
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: {{ .Values.appname }}-secret
              key: DB_NAME