apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.appname }}-ingress
  namespace: {{ .Values.namespace}}
  annotations:
    alb.ingress.kubernetes.io/target-type: {{ .Values.ingress.albTargetType }}
    alb.ingress.kubernetes.io/scheme: {{ .Values.ingress.scheme }}
    alb.ingress.kubernetes.io/tags: Owner=Stefan Olabina
    alb.ingress.kubernetes.io/ssl-redirect: '443'
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}], [{"HTTPS": 443}]'
spec:
  ingressClassName: {{ .Values.ingress.className }}
  tls:
  - hosts:
    - {{ .Values.ingress.host }}
  rules:
  - host: {{ .Values.ingress.host}} 
    http:
    paths:
      - path: {{ .Values.ingress.path }}
        pathType: {{ .Values.ingress.pathType }}
        backend:
          service:
            name: {{ .Values.appname }}-service
            port:
              number: {{ .Values.service.port }}