name: Docker Build

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Tag version'
        required: true
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
      - 'v[0-9]+.[0-9]+'
      - 'v[0-9]+'


jobs:
  build-and-push-docker-image:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Log intoGitHub Packages
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login -u "${{ github.actor }}" --password-stdin docker.pkg.github.com

    - name: Choose Tag
      id: tag
      run: |
        if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
          echo "::set-output name=primary_tag::${{ inputs.version }}"
        else
          echo "::set-output name=primary_tag::${{ github.ref_name }}"
        fi
    
    - name: Print Tag Values
      run: |
        echo "Primary tag value: ${{ steps.tag.outputs.primary_tag }}"
    
    - name: Build Docker Image
      run: |
        docker build -t docker.pkg.github.com/${{ github.repository }}/test-app2:${{ steps.tag.outputs.primary_tag }} .

    - name: Push Docker Image with Primary Tag
      run: |
        docker push docker.pkg.github.com/${{ github.repository }}/test-app2:${{ steps.tag.outputs.primary_tag }}

    - name: Tag and Push Docker Image as Latest
      run: |
        docker tag docker.pkg.github.com/${{ github.repository }}/test-app2:${{ steps.tag.outputs.primary_tag }} docker.pkg.github.com/${{ github.repository }}/test-app2:latest
        docker push docker.pkg.github.com/${{ github.repository }}/test-app2:latest

    