# This is a basic workflow that is manually triggered

name: Docker Build

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  build-and-push:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Log intoGitHub Packages
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login -u "${{ github.actor }}" --password-stdin docker.pkg.github.com

    - name: Build and Push Docker Image
      run: |
        docker build -t docker.pkg.github.com/${{ github.repository }}/test-app2:latest .
        docker push docker.pkg.github.com/${{ github.repository }}/test-app2:latest
