name: Docker Build

on:
  workflow_dispatch:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
      - 'v[0-9]+.[0-9]+'
      - 'v[0-9]+'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Log intoGitHub Packages
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login -u "${{ github.actor }}" --password-stdin docker.pkg.github.com

    - name: Choose Tag
      id: tag
      run: |
        if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
          echo "::set-output name=tag::latest"
        else
          echo "::set-output name=tag::${{ github.ref_name }}"
        fi
    
    - name: Print Tag Value
      run: echo "Tag value:${{ steps.tag.outputs.tag }}"
    
    - name: Build and Push Docker Image
      run: |
        docker build -t docker.pkg.github.com/${{ github.repository }}/test-app2:${{ steps.tag.outputs.tag }} .
        docker push docker.pkg.github.com/${{ github.repository }}/test-app2:${{ steps.tag.outputs.tag }}
